ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "optionGroups" JSONB;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "remarksEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "selectedOptions" JSONB;

