import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';

/**
 * Server-issued device identity.
 *
 * The device id is generated by the server on the first API request and
 * delivered to the browser as an HttpOnly cookie. Clients can no longer
 * fabricate a deviceId in the request body, which closes the loophole that
 * allowed anyone to bypass the per-device ordering limit by inventing a new
 * deviceId on every order.
 *
 * Known residual limitation (unavoidable without login): a user can still
 * obtain a brand new device id by clearing cookies / using a fresh browser
 * profile. That is the best possible guarantee for anonymous guests.
 */

export const DEVICE_ID_COOKIE = 'smart_qr_device_id';
const DEVICE_ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

declare global {
  namespace Express {
    interface Request {
      deviceId?: string;
    }
  }
}

function parseCookies(header: string | undefined): Record<string, string> {
  const cookies: Record<string, string> = {};
  if (!header) return cookies;
  for (const part of header.split(';')) {
    const separator = part.indexOf('=');
    if (separator < 0) continue;
    const name = part.slice(0, separator).trim();
    const value = part.slice(separator + 1).trim();
    if (name) cookies[name] = decodeURIComponent(value);
  }
  return cookies;
}

function setDeviceCookie(res: Response, deviceId: string) {
  const isProd = String(process.env.NODE_ENV || '').toLowerCase() === 'production';
  res.setHeader(
    'Set-Cookie',
    `${DEVICE_ID_COOKIE}=${encodeURIComponent(deviceId)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${
      isProd ? '; Secure' : ''
    }`,
  );
}

export function deviceMiddleware(req: Request, res: Response, next: NextFunction) {
  try {
    const cookies = parseCookies(req.headers.cookie);
    const existing = cookies[DEVICE_ID_COOKIE];
    if (existing && DEVICE_ID_PATTERN.test(existing)) {
      req.deviceId = existing;
      return next();
    }

    const deviceId = crypto.randomUUID();
    setDeviceCookie(res, deviceId);
    req.deviceId = deviceId;
    return next();
  } catch {
    // Never block a request because of device identity handling.
    req.deviceId = crypto.randomUUID();
    return next();
  }
}
